services:
  mines:
    #image: quay.io/str_netappontour/mines:latest
    build:
      context: .
    container_name: mines
    restart: unless-stopped
    environment:
      - DEV_FULL_ACCESS=true
    volumes:
      - './css:/mines/css'
      - './to_encrypt:/to_encrypt'
    ports:
      - 3301:8080
  
  quotes:
    image:  quay.io/str_netappontour/tetris-quotes
    build:
      context: quotes/.
    container_name: mines-quotes
    restart: unless-stopped
    ports:
      - 3302:3000
    volumes:
      - './quotes/texts:/quotes'

  nginx:
    image: nginx:latest
    container_name: mines-nginx
    restart: unless-stopped
    ports:
      - 3300:80
    volumes:
      - './nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
 
